### ISSUE TITLE
Loggin Issue

### ISSUE THREAD

**Issue by shivashukla** [tabvn/loopbackCMS#1]
![image](https://cloud.githubusercontent.com/assets/20643742/24485092/a6e2c2dc-151f-11e7-911d-cd3547a05b20.png)
![image](https://cloud.githubusercontent.com/assets/20643742/24485124/d9905e38-151f-11e7-8502-305cfec6df0a.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/20643742/24485171/26668b1a-1520-11e7-9347-f20813f4bce2.png)

![screenshot 6](https://cloud.githubusercontent.com/assets/20643742/24485293/12b2c196-1521-11e7-9bb6-1d77f91d7839.png)

i have follow all steps but it not login or signup.

**Comment by tabvn** [comment]
@shivashukla try check in backend/src/app/shared/api.config.ts 

http://cloud.tabvn.com/0ppcut.png

change path from //0.0.0.0:3000 to http://localhost:3000 

and waiting for Angular cli re-complie i hope it helps,

Best regards,
Toan

**Comment by tabvn** [comment]
I found a bug with router in Angular v4.0 , i 'm fixing now couple minute :)

**Comment by shivashukla** [comment]
![screenshot 7](https://cloud.githubusercontent.com/assets/20643742/24485514/a3950fce-1522-11e7-8fc1-e351faa933d2.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/20643742/24485513/a392c052-1522-11e7-9a95-c68d0083060e.png)

it have same issue please wait........

**Comment by tabvn** [comment]
OK Fixed.
